%% [] = writeSpatialGraphContour(pt,outputFilename,neuriteID,EdgePtRadius,Labels)
% Write line(s) as a AmiraSpatialGraphContour
% One line is defined by at least two points
% Input:
% - pt: 
%       points as elements (NumPoints x 3) 
%       points as cell with each element {NumEdges x 1}(NumPoints x 3)
% - outputFilename
% - neuriteID: (optional; default: 49, other structures)
%       neuriteID as single value
%       neuriteID as elements for each edge (NumEdges x 1)
% - EdgePtRadius: (optional; default: 0)
%       edgePtRadius as single value
%       edgePtRadius as elements (NumPoints x 1)
%       edgePtRadius as cell with each element {NumEdges x 1}(NumPoints x 1)
% - Labels: (optional; default: []) {NumLabels x 1}
%       if empty: use default GraphLabeling
%       if non-empty: use following labeling structure {1 x NumLabels}
%           Labels(n).Color [1 x 3]
%           Labels(n).ID
%           Labels(n).name
%           Note: Labels(n).ID = 0 should be avoided because GraphLabel ID
%               is 0 as well
% 
% Author: Daniel Udvary (Max Planck Institute for Neurobiology of Behavior – caesar)
%
% NOTE replaces writeSpatialGraphContour_old (does not use different contours)
function [] = writeSpatialGraphContour(pt,outputFilename,neuriteID, ...
                EdgePtRadius,Labels)

    if (strcmp(outputFilename(end-2:end), '.am'))
        fname = outputFilename;  
    else
        fname = [outputFilename '.am'];
    end
    
    if ~isa(pt,'cell')
        
        if size(pt,2)~=3
            error('pt has to be Nx3!');
        end
        
        pt = {pt};
    end
    
    numVertex = length(pt)*2;
    numEdges = length(pt);
    numPoints = 0; 
    for i = 1:length(pt)
        numPoints = numPoints + size(pt{i},1);
    end
        
    if nargin < 3
        neuriteID = 49;
    end
    if nargin < 4
        EdgePtRadius = 0;
    end
    if nargin < 5
       Labels = []; % use default GraphLabels 
    end
    
    % Check neuriteID
    if ~isa(neuriteID,'cell') && numel(neuriteID)==1
        constantNeuriteID = 1;
    else
        constantNeuriteID = 0;
    end
    
    if constantNeuriteID==0 && numel(neuriteID)~=numEdges
        error('NeuriteIDs (%d) does not match number of edges (%d)!', ...
                numel(constantNeuriteID),numEdges);
    end
    
    % Check EdgePtRadius
    if ~isa(EdgePtRadius,'cell') && numel(EdgePtRadius)==1
        constantRadius = 1;
    else
        constantRadius = 0;
    end
    
    if constantRadius==0 && ~isa(EdgePtRadius,'cell')
        EdgePtRadius = {EdgePtRadius};
        
        if numel(EdgePtRadius) ~= numel(pt)
            error('Radii (%d) does not match number of points (%d)!', ...
                    numel(EdgePtRadius),numel(pt));
        end
    end
    
    %% Header Information 
    strHeader1 = sprintf(['# AmiraMesh 3D ASCII 2.0\n\n\n' ...
                    'define VERTEX %d\n' ...
                    'define EDGE %d\n' ...
                    'define POINT %d\n\n'], ...
                    numVertex,numEdges,numPoints);
                
    strHeader3 = sprintf(['VERTEX { float[3] VertexCoordinates } @1\n' ...
                        'VERTEX { int GraphLabels } @2\n' ...
                        'EDGE { int[2] EdgeConnectivity } @3\n' ...
                        'EDGE { int NumEdgePoints } @4\n' ...
                        'EDGE { int GraphLabels } @5\n' ...
                        'POINT { float[3] EdgePointCoordinates } @6\n' ...
                        'POINT { float Radius } @7\n\n' ...
                        '# Data section follows']);

    if isempty(Labels) 
        strHeader2 = sprintf( ...
                        ['Parameters {\n' ...
                        '    GraphLabels {\n' ...
                        '        Neuron {\n' ...
                        '            Dendrite {\n' ...
                        '                ApicalDendrite {\n' ...
                        '                    Color 1 0.5 0.5,\n' ...
                        '                    Id 4\n' ...
                        '                }\n' ...
                        '                BasalDendrite {\n' ...
                        '                    Color 0.8 0.4 0.4,\n' ...
                        '                    Id 5\n' ...
                        '                }\n' ...
                        '                Color 1 0 0,\n' ...
                        '                Id 3\n' ...
                        '            }\n' ...
                        '            Axon {\n' ...
                        '                Color 0 0 1,\n' ...
                        '                Id 6\n' ...
                        '            }\n' ...
                        '            Soma {\n' ...
                        '                Color 1 0 0,\n' ...
                        '                Id 7\n' ...
                        '            }\n' ...
                        '            Color 1 0 0,\n' ...
                        '            Id 2\n' ...
                        '        }\n' ...
                        '        Landmark {\n' ...
                        '            Pia {\n' ...
                        '                Color 0 1 0.5,\n' ...
                        '                Id 9\n' ...
                        '            }\n' ...
                        '            Vessel {\n' ...
                        '                Color 1 0.5 0,\n' ...
                        '                Id 10\n' ...
                        '            }\n' ...
                        '            Barrel {\n' ...
                        '                aRow {\n' ...
                        '                    A1 {\n' ...
                        '                        Color 1 0.2 0.2,\n' ...
                        '                        Id 13\n' ...
                        '                    }\n' ...
                        '                    A2 {\n' ...
                        '                        Color 1 0.2 0.2,\n' ...
                        '                        Id 14\n' ...
                        '                    }\n' ...
                        '                    A3 {\n' ...
                        '                        Color 1 0.2 0.2,\n' ...
                        '                        Id 15\n' ...
                        '                    }\n' ...
                        '                    A4 {\n' ...
                        '                        Color 1 0.2 0.2,\n' ...
                        '                        Id 16\n' ...
                        '                    }\n' ...
                        '                    Color 1 0.2 0.2,\n' ...
                        '                    Id 12\n' ...
                        '                }\n' ...
                        '                bRow {\n' ...
                        '                    B1 {\n' ...
                        '                        Color 1 0.25 0.25,\n' ...
                        '                        Id 18\n' ...
                        '                    }\n' ...
                        '                    B2 {\n' ...
                        '                        Color 1 0.25 0.25,\n' ...
                        '                        Id 19\n' ...
                        '                    }\n' ...
                        '                    B3 {\n' ...
                        '                        Color 1 0.25 0.25,\n' ...
                        '                        Id 20\n' ...
                        '                    }\n' ...
                        '                    B4 {\n' ...
                        '                        Color 1 0.25 0.25,\n' ...
                        '                        Id 21\n' ...
                        '                    }\n' ...
                        '                    Color 1 0.25 0.25,\n' ...
                        '                    Id 17\n' ...
                        '                }\n' ...
                        '                cRow {\n' ...
                        '                    C1 {\n' ...
                        '                        Color 1 0.3 0.3,\n' ...
                        '                        Id 23\n' ...
                        '                    }\n' ...
                        '                    C2 {\n' ...
                        '                        Color 1 0.3 0.3,\n' ...
                        '                        Id 24\n' ...
                        '                    }\n' ...
                        '                    C3 {\n' ...
                        '                        Color 1 0.3 0.3,\n' ...
                        '                        Id 25\n' ...
                        '                    }\n' ...
                        '                    C4 {\n' ...
                        '                        Color 1 0.3 0.3,\n' ...
                        '                        Id 26\n' ...
                        '                    }\n' ...
                        '                    C5 {\n' ...
                        '                        Color 1 0.3 0.3,\n' ...
                        '                        Id 27\n' ...
                        '                    }\n' ...
                        '                    C6 {\n' ...
                        '                        Color 1 0.3 0.3,\n' ...
                        '                        Id 28\n' ...
                        '                    }\n' ...
                        '                    Color 1 0.3 0.3,\n' ...
                        '                    Id 22\n' ...
                        '                }\n' ...
                        '                dRow {\n' ...
                        '                    D1 {\n' ...
                        '                        Color 1 0.35 0.35,\n' ...
                        '                        Id 30\n' ...
                        '                    }\n' ...
                        '                    D2 {\n' ...
                        '                        Color 1 0.35 0.35,\n' ...
                        '                        Id 31\n' ...
                        '                    }\n' ...
                        '                    D3 {\n' ...
                        '                        Color 1 0.35 0.35,\n' ...
                        '                        Id 32\n' ...
                        '                    }\n' ...
                        '                    D4 {\n' ...
                        '                        Color 1 0.35 0.35,\n' ...
                        '                        Id 33\n' ...
                        '                    }\n' ...
                        '                    D5 {\n' ...
                        '                        Color 1 0.35 0.35,\n' ...
                        '                        Id 34\n' ...
                        '                    }\n' ...
                        '                    D6 {\n' ...
                        '                        Color 1 0.35 0.35,\n' ...
                        '                        Id 35\n' ...
                        '                    }\n' ...
                        '                    Color 1 0.35 0.35,\n' ...
                        '                    Id 29\n' ...
                        '                }\n' ...
                        '                eRow {\n' ...
                        '                    E1 {\n' ...
                        '                        Color 1 0.4 0.4,\n' ...
                        '                        Id 37\n' ...
                        '                    }\n' ...
                        '                    E2 {\n' ...
                        '                        Color 1 0.4 0.4,\n' ...
                        '                        Id 38\n' ...
                        '                    }\n' ...
                        '                    E3 {\n' ...
                        '                        Color 1 0.4 0.4,\n' ...
                        '                        Id 39\n' ...
                        '                    }\n' ...
                        '                    E4 {\n' ...
                        '                        Color 1 0.4 0.4,\n' ...
                        '                        Id 40\n' ...
                        '                    }\n' ...
                        '                    E5 {\n' ...
                        '                        Color 1 0.4 0.4,\n' ...
                        '                        Id 41\n' ...
                        '                    }\n' ...
                        '                    E6 {\n' ...
                        '                        Color 1 0.4 0.4,\n' ...
                        '                        Id 42\n' ...
                        '                    }\n' ...
                        '                    Color 1 0.4 0.4,\n' ...
                        '                    Id 36\n' ...
                        '                }\n' ...
                        '                greekRow {\n' ...
                        '                    Alpha {\n' ...
                        '                        Color 1 0.1 0.1,\n' ...
                        '                        Id 44\n' ...
                        '                    }\n' ...
                        '                    Beta {\n' ...
                        '                        Color 1 0.1 0.1,\n' ...
                        '                        Id 45\n' ...
                        '                    }\n' ...
                        '                    Gamma {\n' ...
                        '                        Color 1 0.1 0.1,\n' ...
                        '                        Id 46\n' ...
                        '                    }\n' ...
                        '                    Delta {\n' ...
                        '                        Color 1 0.1 0.1,\n' ...
                        '                        Id 47\n' ...
                        '                    }\n' ...
                        '                    Color 1 0.1 0.1,\n' ...
                        '                    Id 43\n' ...
                        '                }\n' ...
                        '                Color 0 1 0,\n' ...
                        '                Id 11\n' ...
                        '            }\n' ...
                        '            Color 0 1 1,\n' ...
                        '            Id 8\n' ...
                        '        }\n' ...
                        '        Id 0,\n' ...
                        '        Color 0 0 0\n' ...
                        '    }\n' ...
                        '    ContentType "HxSpatialGraph"\n' ...
                        '}\n\n']);
    else
        % Use Alternative Header        
        strHeader2 = sprintf([ ...
                            'Parameters {\n' ...
                            '    GraphLabels {\n']);
        for i = 1:length(Labels)
            
            % Error checking
            if ~isfield(Labels(i),'Color')
                Labels(i).Color = [0 0 0];
            else
                if numel(Labels(i).Color)~=3
                   error('Labels(%d).Color is not [1 x 3]',i); 
                end
            end
            if ~isfield(Labels(i),'ID')
                Labels(i).ID = i;
            end
            if ~isfield(Labels(i),'Name')
                Labels(i).Name = ['Label' num2str(i)];
            end
            if (Labels(i).ID==0)
                warning('Label(%d).ID = 0 might cause trouble!',i);
            end
            
            strHeader2 = sprintf(['%s' ...
                '        %s {\n' ...
                '            Color %.2f %.2f %.2f,\n' ...
                '            Id %d\n' ...
                '        }\n'], ...
                    strHeader2, ...
                    Labels(i).Name,Labels(i).Color(:),Labels(i).ID); 
        end
        strHeader2 = sprintf([ ...
                            '%s        Id 0,\n' ...
                            '        Color 0 0 0\n' ...
                            '    }\n' ...
                            '    ContentType "HxSpatialGraph"\n}\n\n'], ...
                        strHeader2);
    end
            
    %% Write to file
    fid = fopen(fname,'w');

    if fid ~= -1
        fprintf(fid,'%s%s%s\n',strHeader1,strHeader2,strHeader3);

        % (1) Vertex Coordinates
        fprintf(fid,'%s\n','@1');
        for i = 1:numEdges
            fprintf(fid,'%e %e %e\n',pt{i}(1,1),pt{i}(1,2),pt{i}(1,3));      
            fprintf(fid,'%e %e %e\n',pt{i}(end,1),pt{i}(end,2),pt{i}(end,3));  
        end
        fprintf(fid,'%s\n','');

        % (2) Vertex GraphLabels
        fprintf(fid,'%s\n','@2');
        for i = 1:numVertex
            if constantNeuriteID==1
                fprintf(fid,'%d\n',neuriteID);
            else
                fprintf(fid,'%f\n',neuriteID(round(i/2)));
            end
        end
        fprintf(fid,'%s\n','');

        % (3) Edge Connectivity
        fprintf(fid,'%s\n','@3');
        for i = 0:numEdges-1
            fprintf(fid,'%d %d\n',2*i,2*i+1);
        end
        fprintf(fid,'%s\n','');

        % (4) NumEdgePoints
        fprintf(fid,'%s\n','@4');
        for i = 1:numEdges
            fprintf(fid,'%d\n',size(pt{i},1));
        end
        fprintf(fid,'%s\n','');

        % (5) Edge GraphLabels
        fprintf(fid,'%s\n','@5');
        for i = 1:numEdges
            if constantNeuriteID==1
                fprintf(fid,'%d\n',neuriteID);
            else
                fprintf(fid,'%f\n',neuriteID(i));
            end
        end
        fprintf(fid,'%s\n','');

        % (6) Edge Coordinates
        fprintf(fid,'%s\n','@6');
        for p = 1:numEdges
            for i = 1:size(pt{p},1)
                fprintf(fid,'%e %e %e\n',pt{p}(i,1),pt{p}(i,2),pt{p}(i,3));
            end
        end
        fprintf(fid,'%s\n','');

        % (7) Edge Points Radius            
        fprintf(fid,'%s\n','@7');
        for p = 1:numEdges
            for i = 1:size(pt{p},1)
                if constantRadius==1
                    fprintf(fid,'%f\n',EdgePtRadius);
                else
                    fprintf(fid,'%f\n',EdgePtRadius{p}(i));
                end
            end
        end
        fprintf(fid,'%s\n','');

        % Close file
        fclose(fid);
    else
        error(['Failed writing ' fname ' to the disk!']); 
    end

end