% Reads .mat files generated by saveInnervationMatrixC2.m
% Then adds INH sublayers and saves those in subfolder CellMatrix_C2/INH_Layer
% 
% Author: Daniel Udvary (Max Planck Institute for Neurobiology of Behavior – caesar)
clear all
close all
clc

matlabPath = 'D:\udvary-et-al-2022\analysis\';
modelID = 'RBC_20';
dataPath = [matlabPath 'data\CellMatrix_C2\'];
load([matlabPath 'data\CellTable_' modelID '.mat'])
idx = strcmp(CellTable.nearest_column,'C2');
CellTable(~idx,:) = [];
idx = strcmp(CellTable.cell_type,'INH');
CellTable(~idx,:) = [];

neuronID = cell(1,6); 
for j = 1:6
    neuronID{j} = CellTable.neuronID(CellTable.layer==j);
end

d = dir([dataPath '*INH*.mat']);

%%
for i = 1:length(d)
    load([dataPath d(i).name]);
    IRef = I; 
    strtmp = strsplit(d(i).name(1:end-4),'_');

    preList = nan;
    if strcmp(strtmp{1},'INH')
        preList = 1:6;
    end
    postList = nan; 
    if strcmp(strtmp{2},'INH')
        postList = 1:6;
    end
    
    for preID = preList
        if ~isnan(preID)
            idxPre = ismember(IRef.PreCellID,neuronID{preID});
            preStr = ['L' num2str(preID) strtmp{1}];
        else
            idxPre = true(size(IRef.PreCellID)); 
            preStr = strtmp{1};
        end
        
        for postID = postList
            if ~isnan(postID)
                idxPost = ismember(IRef.PostCellID,neuronID{postID});
                postStr = ['L' num2str(postID) strtmp{2}];
            else
                idxPost = true(size(IRef.PostCellID)); 
                postStr = strtmp{2};
            end
            
            I.PostCellID = IRef.PostCellID(idxPost);
            I.PreCellID = IRef.PreCellID(idxPre); 
            I.I = IRef.I(idxPre,:); 
            I.I = I.I(:,idxPost); 

            fprintf('%s-%s\n',preStr,postStr);
            save([dataPath 'INH_Layer\' ...
                    preStr '_' postStr '.mat'],'I');
        end
    end
end